Add option to enable multi-stream
jitsi/docker-jitsi-meet pull request #1308
Opened 2022-06-09 13:12 UTC by DanielMcAssey

Adds the option to enable multi-stream

2022-06-09 13:19 UTC, saghul requested changes

2022-06-09 13:21 UTC, DanielMcAssey commented on jvb/rootfs/defaults/jvb.conf
> +{{ $ENABLE_MULTI_STREAM := .Env.ENABLE_OCTO | default "0" | toBool }}
Oops! Sorted

2022-06-15 11:31 UTC, DanielMcAssey commented
Should be good to go now

2022-06-17 15:58 UTC, DanielMcAssey commented on web/rootfs/defaults/settings-config.js
> +config.flags.sourceNameSignaling = true;
Sorted :)

2022-06-17 16:47 UTC, saghul approved these changes
LGTM!

2022-06-17 17:35 UTC, merged