Register jaas account automatically
jitsi/docker-jitsi-meet pull request #1440
Opened 2022-11-15 12:08 UTC by oanaianc

2022-11-15 12:34 UTC, damencho commented
Do we need a copy of that if its available in the web container that holds jitsi-meet?

2022-11-15 13:44 UTC, saghul commented on register-jaas-account.sh
> +WAIT_BEFORE_CHECK=10
Could we lower this to 5?

2022-11-15 13:47 UTC, saghul commented
LEt's put this in web/rootfs/etc/service.d/jaas-account/run

2022-11-15 13:54 UTC, saghul commented
> Do we need a copy of that if its available in the web container that holds jitsi-meet?

It will be adapted to work in the container environment.

2022-11-17 14:37 UTC, saghul requested changes

2022-11-17 14:37 UTC, saghul commented on web/rootfs/etc/services.d/jaas-account/run
> +function check_nginx() {
Since we only use this in 1 place, perhaps better to inline it?

2022-11-17 14:37 UTC, saghul commented on web/rootfs/etc/services.d/jaas-account/run
> +    stop_service
We need to exit here, or maybe just exit in the stop_service function. Here and elsewhere.

2022-11-17 14:37 UTC, saghul commented on register-jaas-account.sh
> +#!/usr/bin/with-contenv bash
Drop this file now?

2022-11-18 13:05 UTC, oanaianc commented on register-jaas-account.sh
> +WAIT_BEFORE_CHECK=10
yes

2022-11-22 12:05 UTC, saghul approved these changes

2022-11-22 12:05 UTC, merged