Ability to configure whiteboard.
jitsi/docker-jitsi-meet pull request #1453
Opened 2022-12-15 03:05 UTC by debendraoli

- Ability to configure whiteboard.
- Replace deprecated es function `substr()` with `substring()`.

2022-12-15 08:29 UTC, saghul commented on web/rootfs/defaults/settings-config.js
> +{{ $WHITEBOARD_COLLAB_SERVER_BASE_URL := .Env.WHITEBOARD_COLLAB_SERVER_BASE_URL | default "" -}}
Can you please rename this to be `WHITEBOARD_COLLAB_SERVER_PUBLIC_URL` ? That would make it analogous to Etherpad, where use the "base" URL when it's builtin, and the other one when it's external.

2022-12-15 08:30 UTC, saghul requested changes
The room_metadata plugin needs to be loaded too. We probably want to do that regardless of the whiteboard option, since it's generic.

2022-12-19 11:54 UTC, saghul approved these changes

2022-12-19 11:54 UTC, merged

2022-12-29 12:46 UTC, andys448 commented
Hi! 

ENV - WHITEBOARD_COLLAB_SERVER_BASE_URL not working correctly. After filling url - generated variable is still empty in web / config.js

2022-12-29 14:25 UTC, debendraoli commented
correct env name is `WHITEBOARD_COLLAB_SERVER_PUBLIC_URL`.

2022-12-29 16:08 UTC, andys448 commented
> correct env name is `WHITEBOARD_COLLAB_SERVER_PUBLIC_URL`.

Thanks! Works fine)

2023-01-11 13:04 UTC, jvkassi commented
Hello, the button whiteboard is only avaible for moderators. Is the default ? Can i change this config  ?

2023-01-11 16:45 UTC, jvkassi commented
i was missing this config 
https://github.com/jitsi/docker-jitsi-meet/pull/1457