feat(alert-manager): Prometheus Alert Manager added with the prometheus service
jitsi/docker-jitsi-meet pull request #1886
Opened 2024-08-22 03:20 UTC by 24kushang

2024-08-26 12:34 UTC, ltorje-8x8 commented on alertmanager/alertmanager.yml
> +# route:
please add the link to the doc about configuring for slack

2024-08-26 14:25 UTC, ltorje-8x8 commented on alertmanager/README.md
please fill with info on how to run

2024-08-26 14:42 UTC, ltorje-8x8 requested changes
add missing doc

2024-11-12 11:52 UTC, saghul commented
Ping?

2025-05-25 02:16 UTC, closed without merging