feat(config): expose JVB API port
jitsi/docker-jitsi-meet pull request #785
Opened 2020-10-13 13:55 UTC by NullIsNot0

I had to expose JVB API port to read Colibri stats (http://jitsi.example.com:8080/colibri/stats) from remote monitoring system. Added nev config variable: `JVB_TCP_MAPPED_API_PORT`

2020-10-26 14:51 UTC, saghul requested changes

2020-10-26 14:51 UTC, saghul commented on docker-compose.yml
> +            - '${JVB_TCP_MAPPED_API_PORT}:8080'
Can you rename this to `JVB_API_PORT`?

2020-10-26 16:27 UTC, NullIsNot0 commented on docker-compose.yml
> +            - '${JVB_TCP_MAPPED_API_PORT}:8080'
Done

2022-01-26 15:05 UTC, Lithimlin commented
Any updates on this? It would be a really helpful addition

2023-10-30 15:50 UTC, aaronkvanmeerten commented
It appears this is now done via JVB_COLIBRI_PORT, so I'm closing this one.  Feel free to re-open if you disagree and want to discuss further.

2023-10-30 15:50 UTC, closed without merging