add a env variable to enable/disable deep linking in config.js
jitsi/docker-jitsi-meet pull request #974
Opened 2021-03-05 18:08 UTC by prayagsingh

2021-04-01 14:46 UTC, saghul requested changes

2021-04-01 14:46 UTC, saghul commented on web/rootfs/defaults/settings-config.js
> +{{ if $DISABLE_DEEP_LINKING -}}
Assign it unconditionally please, since we are using a default value on the template.

2021-04-15 11:08 UTC, prayagsingh commented
@saghul Please review

2021-04-15 11:55 UTC, saghul approved these changes

2021-04-15 11:55 UTC, merged